# company_aliases.py
alias_mapping = {
    "apple": "apple inc",
    "google": "alphabet inc",
    "amazon": "amazon.com inc",
    "microsoft": "microsoft corporation",
    "facebook": "meta platforms inc",
    "tesla": "tesla inc",
    "berkshire hathaway": "berkshire hathaway inc",
    "walmart": "walmart inc",
    "exxonmobil": "exxon mobil corporation",
    "chevron": "chevron corporation",
    "coca-cola": "the coca-cola company",
    "pepsi": "pepsico inc",
    "johnson & johnson": "johnson & johnson",
    "visa": "visa inc",
    "procter & gamble": "procter & gamble company",
    "unitedhealth": "unitedhealth group incorporated",
    "pfizer": "pfizer inc",
    "inteln": "intel corporation",
    "home depot": "the home depot, inc.",
    "at&t": "at&t inc",
    "mcDonald's": "mcdonald's corporation",
    "nike": "nike inc",
    "jpmorgan chase": "jpmorgan chase & co.",
    "bank of america": "bank of america corporation",
    "wells fargo": "wells fargo & company",
    "merck": "merck & co., inc.",
    "oracle": "oracle corporation",
    "abbvie": "abbvie inc",
    "caterpillar": "caterpillar inc",
    "amgen": "amgen inc",
    "boeing": "the boeing company",
    "southwest airlines": "southwest airlines co.",
    "boeing": "the boeing company",
    "abbott": "abbott laboratories",
    "home depot": "the home depot, inc.",
    "general motors": "general motors company",
    "boston scientific": "boston scientific corporation",
    "american electric power": "american electric power company inc",
    "lockheed martin": "lockheed martin corporation",
    "delta airlines": "delta air lines, inc.",
    "target": "target corporation",
    "t-mobile": "t-mobile us, inc.",
    "ibm": "international business machines corporation",
    "honeywell": "honeywell international inc",
    "kraft heinz": "kraft heinz company",
    "3m": "3m company",
    "airbus": "airbus se",
    "bp": "bp plc",
    "shell": "royal dutch shell plc",
    "tesla": "tesla, inc.",
    "spacex": "spacex",
    "general electric": "general electric company",
    "starbucks": "starbucks corporation",
    "autodesk": "autodesk, inc.",
    "salesforce": "salesforce.com, inc.",
    "citi": "citigroup inc",
    "goldman sachs": "goldman sachs group, inc.",
    "apple inc": "apple inc",
    "alphabet": "alphabet inc"
}

